In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df=pd.read_csv("insurance.csv")

In [ ]:
df.shape

(1338, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.replace({'sex':{'male':1,'female':0}},inplace=True)
df.replace({'smoker':{'yes':1,'no':0}},inplace=True)
df.replace({'region':{'northeast':1,'northwest':2,'southeast':3,'southwest':4}},inplace=True)

In [ ]:
df['region'].unique()

array([4, 3, 2, 1])

In [ ]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       4  16884.92400
1      18    1  33.770         1       0       3   1725.55230
2      28    1  33.000         3       0       3   4449.46200
3      33    1  22.705         0       0       2  21984.47061
4      32    1  28.880         0       0       2   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       2  10600.54830
1334   18    0  31.920         0       0       1   2205.98080
1335   18    0  36.850         0       0       3   1629.83350
1336   21    0  25.800         0       0       4   2007.94500
1337   61    0  29.070         0       1       2  29141.36030

[1338 rows x 7 columns]

In [ ]:
x=df.drop('charges',axis=1)
y=df['charges']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

ValueError: ignored

In [ ]:
model.score(x_test,y_test)

0.778293784216272

In [ ]:
x_train.shape

(936, 6)

In [ ]:
y_test

12       1826.84300
306     20177.67113
318      7421.19455
815      1877.92940
157     15518.18025
           ...     
710      1727.54000
1005     4433.38770
389      4618.07990
923      4320.41085
1164     7153.55390
Name: charges, Length: 402, dtype: float64

In [ ]:
pred=model.predict(x_test)

In [ ]:
pred=pd.DataFrame(pred)

In [ ]:
from sklearn.metrics import mean_squared_error
print(np.sqrt(mean_squared_error(y_test,pred)))

5673.731608537649


In [ ]:
n=model.predict([[19,0,27.900,0,1,4]])
n

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25203.43975516])

In [ ]:
x_train

age  sex     bmi  children  smoker  region
966    51    1  24.795         2       1       2
522    51    0  33.915         0       0       1
155    44    1  39.520         0       0       2
671    29    0  31.160         0       0       1
1173   38    1  29.260         2       0       2
...   ...  ...     ...       ...     ...     ...
802    21    1  22.300         1       0       4
53     36    1  34.430         0       1       3
350    57    0  23.180         0       0       2
79     41    0  32.965         0       0       2
792    22    0  23.180         0       0       1

[936 rows x 6 columns]

In [ ]:
x_test

age  sex     bmi  children  smoker  region
12     23    1  34.400         0       0       4
306    28    0  27.500         2       0       4
318    44    0  27.645         0       0       2
815    20    0  31.460         0       0       3
157    18    1  25.175         0       1       1
...   ...  ...     ...       ...     ...     ...
710    18    1  35.200         1       0       3
1005   29    1  31.730         2       0       2
389    24    0  30.210         3       0       2
923    34    1  35.815         0       0       2
1164   41    0  28.310         1       0       2

[402 rows x 6 columns]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model2= RandomForestRegressor(n_estimators = 100, random_state = 0)
model2.fit(x_train, y_train)

RandomForestRegressor(random_state=0)

In [ ]:
model2.score(x_test,y_test)

0.8480501211093798

In [ ]:
pred=model2.predict(x_test)
print(np.sqrt(mean_squared_error(y_test,pred)))

4697.102446589368


In [ ]:
n=model2.predict([[19,0,27.900,0,1,4]])
n

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([16935.6687576])

In [ ]:
from xgboost import XGBRegressor
model3=XGBRegressor()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.8350647480479628

In [ ]:
pred=model3.predict(x_test)
print(np.sqrt(mean_squared_error(y_test,pred)))

4893.691609063037


In [ ]:
from sklearn.tree import DecisionTreeRegressor
model4=DecisionTreeRegressor()
model4.fit(x_train,y_train)
model4.score(x_test,y_test)

0.6570293934108221

In [ ]:
pred=model4.predict(x_test)
print(np.sqrt(mean_squared_error(y_test,pred)))

7056.808044463669


In [ ]:
n=model.predict([[19,0,27.900,0,1,4]])
n

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25203.43975516])